name: fvsrn
channels:
  - pytorch
  - plotly
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - absl-py=0.15.0=pyhd3eb1b0_0
  - aiohttp=3.8.1=py38h7f8727e_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - asciitree=0.3.3=py_2
  - astropy=5.0.4=py38hce1f21e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py38h06a4308_0
  - bokeh=1.4.0=py38h32f6830_1
  - bottleneck=1.3.2=py38h5c078b8_3
  - brotli=1.0.9=he6710b0_2
  - brotli-python=1.0.9=py38h709712a_5
  - brotlipy=0.7.0=py38h27cfd23_1003
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.4.26=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cartopy=0.18.0=py38h0d9ca2b_1
  - certifi=2021.10.8=py38h06a4308_2
  - cf_xarray=0.7.2=pyhd8ed1ab_0
  - cffi=1.14.6=py38h400218f_0
  - cftime=1.5.1.1=py38hce1f21e_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - cryptography=3.4.8=py38hd23ed53_0
  - cudatoolkit=11.1.1=h6406543_8
  - curl=7.78.0=h1ccaba5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dash=2.2.0=pyhd8ed1ab_0
  - dash-core-components=2.0.0=pyhd8ed1ab_1
  - dash-html-components=2.0.0=pyhd8ed1ab_1
  - dask=2021.10.0=pyhd8ed1ab_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2021.10.0=py38h06a4308_0
  - docrep=0.3.2=pyh44b312d_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.1=h2531618_2
  - fasteners=0.16=pyhd8ed1ab_0
  - flask=2.0.3=pyhd8ed1ab_0
  - flask-compress=1.11=pyhd8ed1ab_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.2.0=py38h7f8727e_0
  - fsspec=2022.1.0=pyhd8ed1ab_0
  - future=0.18.2=py38_1
  - geos=3.8.0=he6710b0_0
  - glib=2.69.1=h5202010_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.42.0=py38hce63b2e_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=3.6.0=py38ha0f2276_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.6=hb1b8bf9_0
  - heapdict=1.0.1=py_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.6.1=py38_0
  - importlib-metadata=4.8.2=py38h06a4308_0
  - importlib_metadata=1.5.0=py38_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py38h06a4308_0
  - ipython=8.3.0=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - itsdangerous=2.1.1=pyhd8ed1ab_0
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=4.4.0=py38h06a4308_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.2.2=py38h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.19.2=hcc1bbae_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcurl=7.78.0=h0b77cf5_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libnetcdf=4.6.1=h2053bdc_4
  - libnghttp2=1.43.0=h812cca2_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.0.10=hc3755c2_1005
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.42.0=h7f98852_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.3.4=py38h06a4308_0
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib=3.4.3=py38h06a4308_0
  - matplotlib-base=3.4.3=py38hbbc1b5f_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h497a2fe_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h1abd341_0
  - monotonic=1.5=py_0
  - msgpack-python=1.0.2=py38hff7bd54_1
  - multidict=5.2.0=py38h7f8727e_2
  - munkres=1.1.4=py_0
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.4.4=py38h06a4308_0
  - nbformat=5.3.0=py38h06a4308_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=py38h06a4308_0
  - netcdf4=1.5.7=py38h0a24e14_0
  - networkx=2.7.1=pyhd3eb1b0_0
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.4.11=py38h06a4308_0
  - numcodecs=0.9.1=py38h295c915_0
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1n=h7f8727e_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.2.5=py38h1abd341_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=6.2.1=py38h6b7be26_0
  - pip=21.2.4=py38h06a4308_0
  - plotly=5.6.0=py_0
  - proj=6.2.1=hc80f0dc_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protobuf=3.19.1=py38h295c915_0
  - psutil=5.8.0=py38h27cfd23_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyerfa=2.0.0=py38h27cfd23_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.1.0=py38h06a4308_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - pyshp=2.3.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.0=py3.8_cuda11.1_cudnn8.0.5_0
  - pytz=2021.3=pyhd8ed1ab_0
  - pywavelets=1.3.0=py38h7f8727e_0
  - pyyaml=5.4.1=py38h497a2fe_0
  - pyzmq=22.3.0=py38h295c915_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-image=0.19.2=py38h51133e4_0
  - scikit-learn=1.0.2=py38h51133e4_1
  - scipy=1.7.3=py38hc147768_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38h06a4308_0
  - shapely=1.7.1=py38h1728cc4_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyh6c4a22f_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.0=py38h7f8727e_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tenacity=8.0.1=py38h06a4308_0
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.0=py38hca6d32c_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - terminado=0.13.1=py38h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - torchaudio=0.8.0=py38
  - torchvision=0.2.2=py_3
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wget=1.20.1=h20c2e04_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38h06a4308_0
  - xarray=0.20.2=pyhd8ed1ab_0
  - xrft=1.0.0=pyhd8ed1ab_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h27cfd23_0
  - zarr=2.10.3=pyhd8ed1ab_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h9c3ff4c_5
  - zfpy=0.5.5=py38h51da96c_5
  - zict=2.0.0=py_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=ha95c52a_0
